import React, {useRef, useState} from 'react';
import {PageContainer, ProTable} from '@ant-design/pro-components';
import {Button, Image, Input, message, Modal, Space, Tag} from 'antd';
import {getStaffPublicCards, reviewStaffPublicCard} from '@/services/api';

const statusMap:any={DRAFT:{text:'草稿',color:'default'},PENDING:{text:'待审核',color:'processing'},APPROVED:{text:'已通过',color:'success'},REJECTED:{text:'已驳回',color:'error'}};
export default function StaffCardsPage(){
  const actionRef=useRef<any>();const [record,setRecord]=useState<any>(null);const [remark,setRemark]=useState('');const [loading,setLoading]=useState(false);
  const review=async(status:'APPROVED'|'REJECTED')=>{if(status==='REJECTED'&&!remark.trim()){message.warning('驳回时请填写原因');return;}try{setLoading(true);await reviewStaffPublicCard(record.id,{status,reviewRemark:remark});message.success(status==='APPROVED'?'审核通过':'已驳回');setRecord(null);setRemark('');actionRef.current?.reload();}catch(e:any){message.error(e?.message||'审核失败')}finally{setLoading(false)}};
  const columns:any[]=[{title:'头像',dataIndex:'avatarUrl',search:false,width:76,render:(v:any)=><Image width={48} height={48} style={{borderRadius:12,objectFit:'cover'}} src={v}/>},{title:'展示名称',dataIndex:'displayName'},{title:'账号',search:false,render:(_:any,r:any)=><div>{r.user?.name||'-'}<br/><span style={{color:'#999'}}>{r.user?.phone||''}</span></div>},{title:'标语',dataIndex:'slogan',search:false,ellipsis:true},{title:'游戏',dataIndex:'gameTags',search:false,render:(v:any)=><Space wrap>{(Array.isArray(v)?v:[]).map((x:string)=><Tag key={x}>{x}</Tag>)}</Space>},{title:'状态',dataIndex:'status',valueEnum:statusMap,render:(_:any,r:any)=><Tag color={statusMap[r.status]?.color}>{statusMap[r.status]?.text||r.status}</Tag>},{title:'提交时间',dataIndex:'submittedAt',valueType:'dateTime',search:false},{title:'操作',valueType:'option',render:(_:any,r:any)=>[<Button key='review' type='link' onClick={()=>{setRecord(r);setRemark('')}}>审核</Button>]}];
  return <PageContainer><ProTable rowKey='id' actionRef={actionRef} columns={columns} request={async(params)=>{const data:any=await getStaffPublicCards(params.status);return{data:Array.isArray(data)?data:[],success:true}}}/><Modal title='服务者公开名片审核' open={!!record} onCancel={()=>setRecord(null)} confirmLoading={loading} footer={[<Button key='reject' danger onClick={()=>review('REJECTED')}>驳回</Button>,<Button key='approve' type='primary' onClick={()=>review('APPROVED')}>通过并公开</Button>]}><p><b>{record?.displayName}</b> · {record?.slogan}</p><p style={{whiteSpace:'pre-wrap'}}>{record?.bio||'暂无介绍'}</p><Input.TextArea rows={3} value={remark} onChange={(e)=>setRemark(e.target.value)} placeholder='审核备注；驳回时必填'/></Modal></PageContainer>
}
